### ISSUE TITLE
Error when connecting BTCPay to iOS

### ISSUE THREAD

**Issue by pavlenex** [IndieSquare/pebblewallet#1]
Can't connect with iOS 12.1.4.

Haven't tried android. Replicated on multiple instances of BTCPay.

![screen shot 2019-03-06 at 12 41 34](https://user-images.githubusercontent.com/36959754/53878848-39346b80-400d-11e9-969e-57ae76216182.png)

**Comment by mandelmonkey** [comment]
@pavlenex thanks
any more info you can supply? do you know what version of btcpay you are running? recent/old etc

you are following the instructions here correct?
https://www.pebble.indiesquare.me/remotenode

**Comment by pavlenex** [comment]
Latest BTCPay. Yep, all correct. Will try to replicate on Android in few hours.

**Comment by mandelmonkey** [comment]
thanks, if one of your btcpay servers isnt valuable and you could share the linking qrcode that would be great if not no worriers

**Comment by pavlenex** [comment]
Sure @mandelmonkey can you come to BTCPay's mattermost and dm me for credentials of the test server. Also Zap developers [opened an issue ](https://github.com/btcpayserver/btcpayserver/issues/656) so it may as well be on our end. Looking into it.

**Comment by mandelmonkey** [comment]
yes I think that may be it, I scanned that url in that issue and got the same error message

**Comment by mandelmonkey** [comment]
fixed by btcpay update
