### ISSUE TITLE
Android-BTCPay "error pairing, please try again"

### ISSUE THREAD

**Issue by JeffVandrewJr** [IndieSquare/pebblewallet#3]
Using Pebble on Android, freshly updated BTCPay. On any pair attempt, I get "error pairing, please try again." No other info. Same error if I manually enter config URL.

**Comment by mandelmonkey** [comment]
Are you able to share the config url? so I can see the format, removing any sensitive nonce used in it of course

**Comment by mandelmonkey** [comment]
also any info on your btcpay setup would be great, OS, btcpay version/commit etc

**Comment by JeffVandrewJr** [comment]
@mandelmonkey BTCPay is the LunaNode one click install (Ubuntu). 

When manually typing URL, I tried:

```
config=https://btcpay.vandrew.com/lnd-config/XXXXXXXXXXXX/lnd.config

https://btcpay.vandrew.com/lnd-config/XXXXXXXXXXX/lnd.config

And also

btcpay.vandrew.com/lnd-config/XXXXXXXXXXXX/lnd.config
```

**Comment by mandelmonkey** [comment]
thanks, maybe an issue with lunanode and btcpay and ports, do you know if it worked with any other wallet? (not sure if there are any on android), or have you tried zap desktop via download the certs and macaroon?

**Comment by JeffVandrewJr** [comment]
@mandelmonkey Zap is having the same issue for me. I'll post in BTCPay mattermost.

**Comment by mandelmonkey** [comment]
thanks!

**Comment by NicolasDorier** [comment]
So I tried, it works for me. Maybe your link it expired?
I also got my LND down recently. LND has been acting strange.

**Comment by JeffVandrewJr** [comment]
It's a problem with the macaroons in my particular lnd instance, so closing.

**Comment by NicolasDorier** [comment]
@JeffVandrewJr you needed to renew the macaroon?

**Comment by NicolasDorier** [comment]
Probably this would fix https://docs.btcpayserver.org/faq-and-common-issues/faq-lightningnetwork#lnd-connection-issues-after-an-update

**Comment by JeffVandrewJr** [comment]
@NicolasDorier I actually did delete all my macaroons and TLS certs. When I restart, it generates new ones in the correct place, but they still don't work.
